# Site settings
title: My ePortfolio
description: This is my personal portfolio site.
url: "https://tekibotz.github.io"

# Markdown options
markdown: kramdown

# Theme settings (Jekyll theme)
theme: jekyll-theme-minimal

# Exclude folders/files from the build
exclude:
  - node_modules
