version: '3.9'
services:
  AAC-database:
    image: mongo
    ports:
      - '27017:27017'
  shelter-backend:
    build: backend/
    environment:
      - PORT=3000
      - DATABASE_URL=mongodb://host.docker.internal:27017/AAC
    ports:
      - '3000:3000'
    depends_on:
      - AAC-database
  shelter-frontend:
    build:
      context: .
      args:
        VITE_BACKEND_URL: http://localhost:3000/api/v1
    ports:
      - '3001:80'
    depends_on:
      - shelter-backend
